gui:
  authorColors:
    'Ian Chesal': 'green'
    '*': '#0000ff'
  branchColors:
    'production': 'red'
  showIcons: true
 # Use the mocha catppuccin theme
  theme:
   activeBorderColor:
     - '#89b4fa'
     - bold
   inactiveBorderColor:
     - '#a6adc8'
   optionsTextColor:
     - '#89b4fa'
   selectedLineBgColor:
     - '#313244'
   selectedRangeBgColor:
     - '#313244'
   cherryPickedCommitBgColor:
     - '#45475a'
   cherryPickedCommitFgColor:
     - '#89b4fa'
   unstagedChangesColor:
     - '#f38ba8'
   defaultFgColor:
     - '#cdd6f4'
   searchingActiveBorderColor:
     - '#f9e2af'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: 'nvim'
notARepository: 'quit'
update:
  method: 'never' # brew keeps it up to date
confirmOnQuit: false

customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true