[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/rubiin/init.lua.git"
    refreshPeriod = "168h"
[".config/mpv"]
    type = "git-repo"
    url = "https://github.com/tsubajashi/mpv-settings.git"
    refreshPeriod = "168h"
