[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/rubiin/init.lua.git"
    refreshPeriod = "168h"
[".config/mpv"]
    type = "git-repo"
    url = "https://github.com/tsubajashi/mpv-settings.git"
    refreshPeriod = "168h"
["~/personal-vim-plugs/fortune.nvim"]
    type = "git-repo"
    url = "https://github.com/rubiin/fortune.nvim.git"
    refreshPeriod = "168h"
["~/personal-vim-plugs/highlighturl.nvim"]
    type = "git-repo"
    url = "https://github.com/rubiin/highlighturl.nvim.git"
    refreshPeriod = "168h"
["~/personal-vim-plugs/vimwordlist.nvim"]
    type = "git-repo"
    url = "https://github.com/rubiin/vimwordlist.nvim.git"
    refreshPeriod = "168h"
