max-gamma = 150

#Day profile (establish normal colors) #this is the new profile
profile {
time = 06:00
identity = true
}

#Night Profile #this is the profile the update has
profile {
time = 18:00
temperature = 3000
gamma = 0.8
}

