#!/usr/bin/env bash

## Author  : Rubin Bhandari (rubiin)
## Mail    : roobin.bhandari@gmail.com
## Github  : @rubiin
## Twitter : @RubinCodes


# abort if we're already inside a TMUX session
[ "$TMUX" == "" ] || exit 0

# present menu for the user to choose which workspace to open
PS3="Please choose your session: "
# shellcheck disable=SC2207
options=($(tmux list-sessions -F "#S" 2>/dev/null) "New Session" "Kill All")
echo "Available sessions"
echo "------------------"
echo " "
select opt in "${options[@]}"; do
	case $opt in
	"New Session")
		read -rp "Enter new session name (random session name if empty): " SESSION_NAME
		SESSION_NAME=${SESSION_NAME:-$(openssl rand -base64 2)}
		tmux new -s "$SESSION_NAME"
		break
		;;
	"Kill All")
		pkill -f tmux
		break
		;;
	*)
		tmux attach-session -t "$opt"
		break
		;;
	esac
done
