#!/bin/sh

# Define the mappings of applications to their designated workspaces
hyprctl dispatch exec [workspace 1  silent] Vivaldi-stable
hyprctl dispatch exec [workspace 2  silent] org.wezfurlong.wezterm
hyprctl dispatch exec [workspace 3  silent] code-insiders-url-handler
hyprctl dispatch exec [workspace 4  silent] Postman
hyprctl dispatch exec [workspace 4  silent] "MongoDB Compass"
hyprctl dispatch exec [workspace 5  silent] org.kde.dolphin


## add teams and other
