#!/bin/bash
# Pick a preconfigured theme
FONT=$(fc-list : family | awk -F "," '{ if (NF>1) print $2 }' | sort | fzf)

echo "$FONT"

## change kitty font

sed -i "s/font_family.*/font_family    '$FONT'/" ~/.config/kitty/kitty.conf

## change wezterm font
## change vscode font
