"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[volume]
# volumecontrol.sh configuration
notify = false    # Useful for systems that have their own OSD
steps = 5         # Number of steps to increase/decrease volume
boost = true      # Enable volume boost
boost_limit = 150 # Volume boost limit // Don't kill your ears/speakers

[brightness]
notify = false # Useful for systems that have their own OSD
steps = 5


[battery.notify.threshold]
full = 100
critical = 10
low = 20
unplug = 80


[battery.notify]
timer = 120
notify = 1140
interval = 5
dock = true

[battery.notify.execute]
critical = "systemctl suspend"

[screenshot]
annotation_enabled = true
annotation_tool = "satty"

[wallpaper]
custom_paths = [
    "$HOME/Pictures/Wallpapers",
] # List of paths to search for wallpapers


[hyprland]
browser = "vivaldi"  # Browser.
editor = "code-insiders" # Editor.
terminal = "wezterm"     # Terminal.
quickapps = "wezterm"    # Quick apps.
explorer = "dolphin"


[hyprland-start]
bar = ''
apptray_bluetooth = ''

