# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"


[[mgr.prepend_keymap]]
on = "j"
run = ["plugin --sync arrow --args=1"]
desc = "Move selection downwards, or wrap."

[[mgr.prepend_keymap]]
on = "k"
run = ["plugin --sync arrow --args=-1"]
desc = "Move selection upwards, or wrap."

[[mgr.prepend_keymap]]
on = "l"
run = ["plugin smart-enter --sync", "escape --visual --select"]
desc = "Enter the child directory, or open file."

[[mgr.prepend_keymap]]
on = "L"
run = "plugin smart-enter --sync --args='detach'"
desc = "Open in new window."

[[mgr.prepend_keymap]]
on = "="
run = """
shell 'printf "Mode Bits: "; read ans; chmod $ans "$@"' --block --confirm
"""
desc = "chmod"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"
