# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# check here for https://github.com/sxyazi/dotfiles/blob/main/yazi/yazi.toml
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 1, 2, 3 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
linemode       = "size"
show_hidden    = true
show_symlink   = true

[preview]
tab_size        = 2
max_width       = 1500
max_height      = 1500
cache_dir       = ""
image_filter    = "triangle"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]
edit = [
	{ run = '${EDITOR:=vi} "$@"', desc = "$EDITOR", block = true },
	{ run = 'code "$@"', orphan = true },
]
play = [
	{ run = 'mpv --force-window "$@"', orphan = true },
	{ run = 'vlc "$@"', orphan = true }
]
extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
reveal = [
    { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
    { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]

[open]
prepend_rules = [
    # Folder
    { name = "*/", use = ["edit", "open", "reveal"] },
    # Text
    { mime = "text/*", use = ["edit", "reveal"] },
    # Image
    { mime = "image/*", use = ["open", "reveal"] },
    # Media
    { mime = "{audio,video}/*", use = ["play", "reveal"] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = ["extract", "reveal"] },
    # JSON
    { mime = "application/{json,ndjson}", use = ["edit", "reveal"] },
    { mime = "*/javascript", use = ["edit", "reveal"] },
    # Empty file
    { mime = "inode/empty", use = ["edit", "reveal"] },
    # Fallback
    { name = "*", use = ["open", "reveal"] },
]