
[settings]
lockfile = true
# whether to prompt to install plugins and runtimes if they're not already installed
# missing_runtime_behavior = 'autoinstall' # other options: 'ignore', 'warn', 'prompt', 'autoinstall'

# plugins can read the versions files used by other version managers (if enabled by the plugin)
# for example, .nvmrc in the case of nodejs's nvm
legacy_version_file = true # enabled by default (different than asdf)

# configure `mise install` to always keep the downloaded archive
always_keep_download = false # deleted after install by default
always_keep_install = false  # deleted on failure by default

# configure how frequently (in minutes) to fetch updated plugin repository changes
# this is updated whenever a new runtime is installed
# (note: this isn't currently implemented but there are plans to add it: https://github.com/jdxcode/rtx/issues/128)
plugin_autoupdate_last_check_duration = '1 week' # set to 0 to disable updates

verbose = false # set to true to see full installation output, see `RTX_VERBOSE`
asdf_compat = false # set to true to ensure .tool-versions will be compatible with asdf, see `RTX_ASDF_COMPAT`
jobs = 8 # number of plugins or runtimes to install in parallel. The default is `8`.
raw = false # set to true to directly pipe plugins to stdin/stdout/stderr
experimental = true
idiomatic_version_file_enable_tools = [
  "node",
  "python",
  "pnpm",
  "npm",
  "bun",
  "deno",
  "go",
  "yarn",
]
python.compile = false # always download precompiled binaries
color_theme = "catppuccin"
pipx.uvx = true
gpg_verify = true
npm.package_manager = "pnpm"

# shims_dir = '~/.local/share/rtx/shims' # [experimental] directory where shims are stored

[tools]
go = "latest"
rust = "latest"
ruby = "latest"
uv = "latest"
node = "24"
usage = "latest"
deno = "latest"
ruff = "latest"
gallery-dl = "latest"
cargo-binstall = "latest"
prek = "latest"
pi = "latest"
gum = "latest"


# npm plugins
"npm:@nestjs/cli" = "latest"
"npm:serve" = "latest"
"npm:neovim" = "latest"
"npm:taze" = "latest"
"npm:release-it" = "latest"
"npm:yarn" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:types-installer" = "latest"
"npm:asdfui" = "latest"
"npm:commitizen" = "latest"
"npm:cz-conventional-changelog" = "latest"
"npm:nfdl" = "latest"
"npm:autocannon" = "latest"
"npm:sass" = "latest"
"npm:gitpick" = "latest"
"npm:aaja" = "latest"
"npm:json-server" = "latest"
"npm:pnpm" = "latest"
"npm:oxlint" = "latest"
"npm:oxfmt" = "latest"
"npm:fallow" = "latest"
"npm:localtunnel" = "latest"
"npm:npkill" = "latest"


# go tools
"go:github.com/Gelio/go-global-update" = "latest"


# cargo plugins
"cargo:cargo-update" = "latest"
"cargo:momoisay" = "latest"

# pipx plugins
"pipx:urlscan" = "latest"
"pipx:instaloader" = "latest"
"pipx:konsave" = "latest"
"pipx:notebook" = "latest"
"pipx:git-revise" = "latest"
"pipx:iredis" = "latest"
"pipx:xxh-xxh" = "latest"
"pipx:yt-dlp" = "latest"
"pipx:glances" = "latest"

# github plugins
"github:adaszko/complgen" = "latest"
"github:loichyan/nerdfix" = "latest"
"github:max-niederman/ttyper" = "latest"
"github:joshmedeski/sesh" = "latest"
"github:boyter/scc" = "latest"
"github:isorensen/hyprflow" = { version = "latest", asset_pattern = "hyprflow" }
"pipx:subliminal" = "latest"

"aqua:iffse/pay-respects" = "latest"
